// <auto-generated />
namespace UniversityofLouisvilleVaccine.DataContexts.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class SecondCreate1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecondCreate1));
        
        string IMigrationMetadata.Id
        {
            get { return "201503021915459_SecondCreate1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
